message: "Hello from Production Environment"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: "{cipher}AYBP8hhgzLEL1mSazUQJoCVGzr4uh2L1ghMThB8oBmUVg43F6dAfBHyE7TTE9dVHboNC+YoZ8noZZFc1yEiXgEdWVsgyhfLsmAF1H3rz7u6MNxhSveTaDbH/VSZPQRQXzytERTX/3mYKUQMR2fetb82ZTS4Shv9uW6tDGyy0SxXU7lNooaFzAK9kqxx1hvM9kJ0ccmd/NieXrEU/SyNs7O0mwZ5ZjRCyAb2eqcM5QiOau5oAaLaJbYUuvskj/blkY/nk1TMl8bzREAKgzAUlPjPXDVoIX39KxullgZDY/qS5XrkJ4uGucpR+WMYEUAbSrFMuZq3iCdG+LuTjpC+U40cFTAZiZ1jxiyNAqO3Yclh/ht4ZpLyz/uzl9iUkyeuRsxZfXvyNFQoeX/+xX46mN4W8JsahZ3+Gh5bQaxZHJJzB2irlPZqZYhE45IxumCdVEAkoZaxwYASM33flNxLVL07ExzKTvYWetYVJpdcLgEtzaDFrHhmGltR1lkEGKDlJOwGbCivvG2om/UYdBqs3UqKdRdmunSYAUmA+xgxZ5LiebYhnGZZ+gPYlMs+XjyrWr64="
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8091
